# Generated by Django 3.2 on 2023-03-25 15:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Darasa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Excuse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruhusayanini', models.CharField(max_length=8000)),
                ('issued_at', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Mkondo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stream_name', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='MwalimuProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=500, unique=True)),
                ('category', models.CharField(default='Teacher', max_length=80)),
                ('is_user_created', models.BooleanField(default=False)),
                ('full_name', models.CharField(blank=True, max_length=300, null=True)),
                ('gender', models.CharField(blank=True, max_length=500, null=True)),
                ('ni_mwalimu_wa_darasa', models.BooleanField(default=False)),
                ('register_date', models.CharField(max_length=50)),
                ('darasa_lake', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mwalimu', to='organization.darasa')),
                ('madarasa_anoyofundisha', models.ManyToManyField(blank=True, related_name='mfundishaji', to='organization.Darasa')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('photo', models.ImageField(upload_to='images/')),
                ('birth_date', models.CharField(max_length=500)),
                ('gender', models.CharField(max_length=50)),
                ('role', models.CharField(max_length=500)),
                ('register_date', models.CharField(max_length=50)),
                ('excuse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organization.excuse')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='SubjectResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('submitted_at', models.CharField(max_length=800)),
                ('muhula', models.CharField(blank=True, max_length=50, null=True)),
                ('mark', models.PositiveIntegerField()),
                ('darasa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matokeo', to='organization.darasa')),
                ('marked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='results', to='organization.mwalimuprofile')),
                ('somo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='somoresults', to='organization.subject')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studentresult', to='organization.student')),
            ],
        ),
        migrations.CreateModel(
            name='MzaziProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(default='Mzazi', max_length=50)),
                ('student', models.ManyToManyField(blank=True, to='organization.Student')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Matukio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('starting_date', models.CharField(max_length=50)),
                ('ending_date', models.CharField(max_length=50)),
                ('darasa', models.ManyToManyField(blank=True, to='organization.Darasa')),
            ],
        ),
        migrations.CreateModel(
            name='InstituteProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('country', models.CharField(blank=True, max_length=500, null=True)),
                ('region', models.CharField(blank=True, max_length=500, null=True)),
                ('district', models.CharField(blank=True, max_length=500, null=True)),
                ('type', models.CharField(blank=True, max_length=500, null=True)),
                ('regno', models.CharField(blank=True, max_length=500, null=True)),
                ('name', models.CharField(blank=True, max_length=500, null=True)),
                ('web', models.CharField(blank=True, max_length=500, null=True)),
                ('headname', models.CharField(blank=True, max_length=500, null=True)),
                ('ceo', models.CharField(blank=True, max_length=500, null=True)),
                ('address', models.CharField(blank=True, max_length=500, null=True)),
                ('opentime', models.CharField(blank=True, max_length=500, null=True)),
                ('category', models.CharField(default='Institute', max_length=500)),
                ('isComplete', models.BooleanField(default=False)),
                ('school_level', models.CharField(max_length=50)),
                ('register_date', models.CharField(max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ExamTimeTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=50)),
                ('start_time', models.CharField(max_length=500)),
                ('end_time', models.CharField(max_length=500)),
                ('darasa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='organization.darasa')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organization.subject')),
            ],
        ),
        migrations.AddField(
            model_name='darasa',
            name='students',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.student'),
        ),
        migrations.AddField(
            model_name='darasa',
            name='subclass',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organization.mkondo'),
        ),
        migrations.AddField(
            model_name='darasa',
            name='subjects',
            field=models.ManyToManyField(blank=True, to='organization.Subject'),
        ),
        migrations.CreateModel(
            name='ClassTimeTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=50)),
                ('time', models.CharField(max_length=500)),
                ('anaefundisha', models.ManyToManyField(to='organization.MwalimuProfile')),
                ('darasa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='organization.darasa')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organization.subject')),
            ],
        ),
        migrations.CreateModel(
            name='Attendency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('topic', models.CharField(max_length=50)),
                ('subtopic', models.CharField(blank=True, max_length=50, null=True)),
                ('darasa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='organization.darasa')),
            ],
        ),
    ]
