# Generated by Django 3.2 on 2023-03-28 13:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organization', '0005_mwalimuprofile_iscomplete'),
    ]

    operations = [
        migrations.AddField(
            model_name='mwalimuprofile',
            name='organization',
            field=models.ManyToManyField(blank=True, to='organization.InstituteProfile'),
        ),
        migrations.AddField(
            model_name='mzaziprofile',
            name='name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='mzaziprofile',
            name='profile_is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='mzaziprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mzazi', to=settings.AUTH_USER_MODEL),
        ),
    ]
