# Generated by Django 3.2 on 2023-04-03 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0006_auto_20230328_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='classtimetable',
            name='mkondo',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.mkondo'),
        ),
        migrations.AddField(
            model_name='mwalimuprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='instituteprofile',
            name='register_date',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='instituteprofile',
            name='school_level',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
