# Generated by Django 3.2 on 2023-04-03 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0007_auto_20230403_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='darasa',
            name='students',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.student'),
        ),
    ]
