# Generated by Django 3.2 on 2023-04-06 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0008_alter_darasa_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='mwalimuprofile',
            name='mikondo',
            field=models.ManyToManyField(blank=True, to='organization.Mkondo'),
        ),
    ]
