# Generated by Django 3.2 on 2023-04-06 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0009_mwalimuprofile_mikondo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mwalimuprofile',
            name='mikondo',
            field=models.ManyToManyField(blank=True, related_name='mwalimuprofile', to='organization.Mkondo'),
        ),
        migrations.AlterField(
            model_name='mwalimuprofile',
            name='organization',
            field=models.ManyToManyField(blank=True, related_name='mkufunzi', to='organization.InstituteProfile'),
        ),
    ]
