# Generated by Django 3.2 on 2023-04-06 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0010_auto_20230406_0949'),
    ]

    operations = [
        migrations.AddField(
            model_name='mzaziprofile',
            name='relationship',
            field=models.CharField(default='Parent', max_length=50),
        ),
    ]
