# Generated by Django 3.2 on 2023-04-07 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0013_auto_20230407_0907'),
    ]

    operations = [
        migrations.AddField(
            model_name='darasa',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.instituteprofile'),
        ),
    ]
