# Generated by Django 3.2 on 2023-04-08 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0016_auto_20230408_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolexamtimetable',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='school_timetables', to='organization.instituteprofile'),
        ),
    ]
