# Generated by Django 3.2 on 2023-04-08 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0017_schoolexamtimetable_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendency',
            name='student',
            field=models.ManyToManyField(blank=True, to='organization.Student'),
        ),
    ]
