# Generated by Django 3.2 on 2023-04-08 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0020_alter_attendency_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendency',
            name='student',
        ),
        migrations.AddField(
            model_name='attendency',
            name='mkondo',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.mkondo'),
        ),
        migrations.RemoveField(
            model_name='attendency',
            name='status',
        ),
        migrations.CreateModel(
            name='StudentSubjectAttendanceStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.student')),
            ],
        ),
        migrations.AddField(
            model_name='attendency',
            name='status',
            field=models.ManyToManyField(blank=True, to='organization.StudentSubjectAttendanceStatus'),
        ),
    ]
