# Generated by Django 3.2 on 2023-04-11 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0021_auto_20230408_1601'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjectresult',
            name='muhula',
        ),
        migrations.AddField(
            model_name='subjectresult',
            name='mkondo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matokeoyasomo', to='organization.mkondo'),
        ),
        migrations.AddField(
            model_name='subjectresult',
            name='school_exam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='school_exam_results', to='organization.schoolexamtimetable'),
        ),
        migrations.AlterField(
            model_name='subjectresult',
            name='type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
