# Generated by Django 3.2 on 2023-04-11 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0022_auto_20230411_0934'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.instituteprofile'),
        ),
        migrations.AlterField(
            model_name='subjectresult',
            name='somo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='somoresults', to='organization.subject'),
        ),
    ]
