# Generated by Django 3.2 on 2023-04-19 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0023_auto_20230411_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classtimetable',
            name='anaefundisha',
            field=models.ManyToManyField(blank=True, related_name='classtimetable', to='organization.MwalimuProfile'),
        ),
        migrations.AlterField(
            model_name='classtimetable',
            name='darasa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ratibayadarasa', to='organization.darasa'),
        ),
        migrations.AlterField(
            model_name='classtimetable',
            name='mkondo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ratibayaclass', to='organization.mkondo'),
        ),
    ]
