# Generated by Django 3.2 on 2023-04-19 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0024_auto_20230419_1609'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='classtimetable',
            unique_together={('day', 'subject', 'time', 'mkondo', 'darasa')},
        ),
    ]
