# Generated by Django 3.2 on 2023-04-26 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0025_alter_classtimetable_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='classtimetable',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ratibayashule', to='organization.instituteprofile'),
        ),
    ]
