# Generated by Django 3.2 on 2023-05-04 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0027_auto_20230504_0655'),
    ]

    operations = [
        migrations.AddField(
            model_name='examtimetable',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ratiba_ya_mtihanidarasa', to='organization.instituteprofile'),
        ),
    ]
