# Generated by Django 3.2 on 2023-05-04 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0028_examtimetable_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examtimetable',
            name='darasa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.darasa'),
        ),
    ]
