# Generated by Django 3.2 on 2023-05-12 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0029_alter_examtimetable_darasa'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wanafunzi', to='organization.instituteprofile'),
        ),
        migrations.AlterField(
            model_name='darasa',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.instituteprofile'),
        ),
    ]
