# Generated by Django 3.2 on 2023-05-15 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0030_auto_20230512_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectresult',
            name='totalMarks',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
