# Generated by Django 3.2 on 2023-05-15 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0031_auto_20230515_0857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectresult',
            name='mark',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
