# Generated by Django 3.2 on 2023-05-15 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0032_alter_subjectresult_mark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectresult',
            name='mark',
            field=models.CharField(max_length=50),
        ),
    ]
