# Generated by Django 3.2 on 2023-05-16 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0033_alter_subjectresult_mark'),
    ]

    operations = [
        migrations.AddField(
            model_name='excuse',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ruhusa', to='organization.instituteprofile'),
        ),
        migrations.AlterField(
            model_name='student',
            name='excuse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student', to='organization.excuse'),
        ),
    ]
