# Generated by Django 3.2 on 2023-05-19 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0034_auto_20230516_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectresult',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='majibu', to='organization.instituteprofile'),
        ),
    ]
