# Generated by Django 3.2 on 2023-05-27 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0035_subjectresult_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendency',
            name='mwitaji',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mahundurio', to='organization.mwalimuprofile'),
        ),
        migrations.AlterField(
            model_name='attendency',
            name='darasa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.darasa'),
        ),
        migrations.AlterField(
            model_name='attendency',
            name='mkondo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.mkondo'),
        ),
    ]
