# Generated by Django 3.2 on 2023-06-02 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0036_auto_20230527_0946'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendency',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='attendency',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
