# Generated by Django 3.2 on 2023-11-18 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0037_auto_20230602_0740'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='health',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='nationality',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='religion',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
