# Generated by Django 3.2 on 2023-11-21 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_paymentrecord_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentrecord',
            name='mode',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
