# Generated by Django 3.2 on 2023-11-21 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_paymentrecord_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentrecord',
            name='mode',
            field=models.CharField(blank=True, default='PAID', max_length=1000, null=True),
        ),
    ]
