# Generated by Django 3.2 on 2023-11-21 22:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0005_alter_paymentrecord_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentrecord',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alielipia', to=settings.AUTH_USER_MODEL),
        ),
    ]
