# Generated by Django 3.2 on 2023-11-22 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_paymentrecord_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentrecord',
            name='reference',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
