# Generated by Django 3.2 on 2023-11-24 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_paymentrecord_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionrecord',
            name='metadata',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
