# Generated by Django 3.2 on 2023-11-29 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0038_auto_20230920_0832'),
        ('api', '0009_alter_paymentrecord_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentrecord',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='anaelipiwa', to='organization.student'),
        ),
    ]
