# Generated by Django 3.2 on 2023-11-29 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_paymentrecord_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentrecord',
            name='amount',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
